# Generated by Django 4.1.5 on 2023-01-30 05:44

from django.db import migrations, models
import django.db.models.deletion


def populate_initial(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Bay = apps.get_model("api", "Bay")
    Bay.objects.using(db_alias).bulk_create([Bay(name=f"Bay {i}") for i in range(1, 5)])
    Customer = apps.get_model("api", "Customer")
    Customer.objects.using(db_alias).bulk_create(
        [
            Customer(name=name, license_plate=license)
            for name, license in (
                ("Alice", "ZXCV"),
                ("Bob", "AS3A"),
                ("Charlie", "TY8G"),
                ("Dave", "QWE4"),
            )
        ]
    )


def revert(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Bay = apps.get_model("api", "Bay")
    Bay.objects.using(db_alias).all().delete()
    Customer = apps.get_model("api", "Customer")
    Customer.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField()),
                ("booking_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bay_bookings",
                        to="api.bay",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_bookings",
                        to="api.customer",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_initial, revert),
    ]
